x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: 3

services:
  ######################
  # Consumer services ##
  ######################
  consumer-0:
    image: lblod/delta-consumer:0.0.26
    depends_on:
      - database
      - virtuoso
    restart: always
    volumes:
      - ./config/consumer/custom-dispatching:/config/triples-dispatching/custom-dispatching
    environment:
      DCR_SERVICE_NAME: consumer-0
      DCR_CRON_PATTERN_DELTA_SYNC: 0 * * * * # Every hour
      DCR_START_FROM_DELTA_TIMESTAMP: 2024-10-01
      DCR_SYNC_BASE_URL: https://lokaalbeslist-harvester-0.s.redhost.be/
      DCR_SYNC_FILES_PATH: /sync/besluiten/files
      DCR_SYNC_DATASET_SUBJECT: http://data.lblod.info/datasets/delta-producer/dumps/lblod-harvester/BesluitenCacheGraphDump
      DCR_INITIAL_SYNC_JOB_OPERATION: http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/initialSync/besluiten
      DCR_DELTA_SYNC_JOB_OPERATION: http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/besluitenSyncing
      DCR_JOB_CREATOR_URI: http://data.lblod.info/services/id/besluiten-consumer
      DCR_DISABLE_INITIAL_SYNC: true
      DCR_WAIT_FOR_INITIAL_SYNC: false
      DCR_DISABLE_DELTA_INGEST: false
      INGEST_GRAPH: http://mu.semte.ch/graphs/public
      BATCH_SIZE: 500
    logging: *default-logging
    labels:
      - logging=true
  consumer-1:
    image: lblod/delta-consumer:0.0.26
    depends_on:
      - database
      - virtuoso
    restart: always
    volumes:
      - ./config/consumer/custom-dispatching:/config/triples-dispatching/custom-dispatching
    environment:
      DCR_SERVICE_NAME: consumer-1
      DCR_CRON_PATTERN_DELTA_SYNC: 0 * * * * # Every hour
      DCR_START_FROM_DELTA_TIMESTAMP: 2024-10-01
      DCR_SYNC_BASE_URL: https://lokaalbeslist-harvester-1.s.redhost.be/
      DCR_SYNC_FILES_PATH: /sync/besluiten/files
      DCR_SYNC_DATASET_SUBJECT: http://data.lblod.info/datasets/delta-producer/dumps/lblod-harvester/BesluitenCacheGraphDump
      DCR_INITIAL_SYNC_JOB_OPERATION: http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/initialSync/besluiten
      DCR_DELTA_SYNC_JOB_OPERATION: http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/besluitenSyncing
      DCR_JOB_CREATOR_URI: http://data.lblod.info/services/id/besluiten-consumer
      DCR_DISABLE_INITIAL_SYNC: true
      DCR_WAIT_FOR_INITIAL_SYNC: false
      DCR_DISABLE_DELTA_INGEST: false
      INGEST_GRAPH: http://mu.semte.ch/graphs/public
      BATCH_SIZE: 500
    logging: *default-logging
    labels:
      - logging=true
  consumer-2:
    image: lblod/delta-consumer:0.0.26
    depends_on:
      - database
      - virtuoso
    restart: always
    volumes:
      - ./config/consumer/custom-dispatching:/config/triples-dispatching/custom-dispatching
    environment:
      DCR_SERVICE_NAME: consumer-2
      DCR_CRON_PATTERN_DELTA_SYNC: 0 * * * * # Every hour
      DCR_START_FROM_DELTA_TIMESTAMP: 2024-10-01
      DCR_SYNC_BASE_URL: https://lokaalbeslist-harvester-2.s.redhost.be/
      DCR_SYNC_FILES_PATH: /sync/besluiten/files
      DCR_SYNC_DATASET_SUBJECT: http://data.lblod.info/datasets/delta-producer/dumps/lblod-harvester/BesluitenCacheGraphDump
      DCR_INITIAL_SYNC_JOB_OPERATION: http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/initialSync/besluiten
      DCR_DELTA_SYNC_JOB_OPERATION: http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/besluitenSyncing
      DCR_JOB_CREATOR_URI: http://data.lblod.info/services/id/besluiten-consumer
      DCR_DISABLE_INITIAL_SYNC: true
      DCR_WAIT_FOR_INITIAL_SYNC: false
      DCR_DISABLE_DELTA_INGEST: false
      INGEST_GRAPH: http://mu.semte.ch/graphs/public
      BATCH_SIZE: 500
    logging: *default-logging
    labels:
      - logging=true
  consumer-3:
    image: lblod/delta-consumer:0.0.26
    depends_on:
      - database
      - virtuoso
    restart: always
    volumes:
      - ./config/consumer/custom-dispatching:/config/triples-dispatching/custom-dispatching
    environment:
      DCR_SERVICE_NAME: consumer-3
      DCR_CRON_PATTERN_DELTA_SYNC: 0 * * * * # Every hour
      DCR_START_FROM_DELTA_TIMESTAMP: 2024-10-01
      DCR_SYNC_BASE_URL: https://lokaalbeslist-harvester-3.s.redhost.be/
      DCR_SYNC_FILES_PATH: /sync/besluiten/files
      DCR_SYNC_DATASET_SUBJECT: http://data.lblod.info/datasets/delta-producer/dumps/lblod-harvester/BesluitenCacheGraphDump
      DCR_INITIAL_SYNC_JOB_OPERATION: http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/initialSync/besluiten
      DCR_DELTA_SYNC_JOB_OPERATION: http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/besluitenSyncing
      DCR_JOB_CREATOR_URI: http://data.lblod.info/services/id/besluiten-consumer
      DCR_DISABLE_INITIAL_SYNC: true
      DCR_WAIT_FOR_INITIAL_SYNC: false
      DCR_DISABLE_DELTA_INGEST: false
      INGEST_GRAPH: http://mu.semte.ch/graphs/public
      BATCH_SIZE: 500
    logging: *default-logging
    labels:
      - logging=true
  ######################
  # LDES              ##
  ######################
  ldes-backend:
    image: redpencil/fragmentation-producer:0.4.1
    restart: always
    environment:
      BASE_URL: https://mandaten-besluiten.lblod.info/streams/ldes/
      PAGE_RESOURCES_COUNT: 20
      TIME_TREE_RELATION_PATH: http://www.w3.org/ns/prov#generatedAtTime
      CACHE_SIZE: 10
      DATA_FOLDER: /data
      ENABLE_AUTH: false
    volumes:
      - ./data/ldes-feed/:/data/
    logging: *default-logging
    labels:
      - logging=true
  ldes-delta-pusher:
    image: redpencil/ldes-delta-pusher:1.2.0
    environment:
      LDES_ENDPOINT: http://ldes-backend
      LDES_BASE: https://mandaten-besluiten.lblod.info/streams/ldes
      LDES_FOLDER: public # ignored as we have an ldes config that sets the stream folder
      DATA_FOLDER: /data
      CRON_HEALING: 0 0 0 * * * # Every day at midnight
      AUTO_HEALING: false
      CRON_PATTERN_CLEANUP: '0 */2 * * *' # Every 2 hours
      SUDO_QUERY_RETRY_FOR_HTTP_STATUS_CODES: 429,500,502,503,504
      MAX_PAGE_SIZE_BYTES: 10000000
      INITIAL_STATE_LIMIT: 10000
      DIRECT_DB_ENDPOINT: http://virtuoso:8890/sparql
      WRITE_INITIAL_STATE: false # false as we do not do an initial sync of the consumers
    volumes:
      - ./config/ldes-delta-pusher/:/config/
      - ./data/ldes-feed/:/data/
    restart: always
    links:
      - virtuoso:database
    logging: *default-logging
    labels:
      - logging=true
  ##################
  # Base services ##
  ##################
  identifier:
    image: semtech/mu-identifier:1.10.1
    restart: always
    logging: *default-logging
    labels:
      - logging=true
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    restart: always
    logging: *default-logging
    labels:
      - logging=true
  deltanotifier:
    image: semtech/mu-delta-notifier:0.3.0
    volumes:
      - ./config/delta:/config
    restart: always
    logging: *default-logging
    labels:
      - logging=true
  database:
    image: semtech/sparql-parser:0.0.14
    environment:
      MU_SPARQL_ENDPOINT: http://virtuoso:8890/sparql
      DATABASE_OVERLOAD_RECOVERY: true
      DATABASE_COMPATIBILITY: Virtuoso
      # Note: not sure wether it gets picked up properly, it is meant for healing-process which may make
      # heavy queries
      QUERY_MAX_PROCESSING_TIME: 605000
      QUERY_MAX_EXECUTION_TIME: 605000
      LOG_SERVER_CONFIGURATION: true
      LOG_DELTA_MESSAGES: false
      LOG_OUTGOING_SPARQL_QUERIES: true
      LOG_INCOMING_SPARQL_QUERIES: true
      LOG_TEMPLATE_MATCHER_PERFORMANCE: false
      LOG_ACCESS_RIGHTS: false
      INSPECT_ACCESS_RIGHTS_PROCESSING: false
    volumes:
      - ./config/cl-authorization:/config
      - ./data/mu-auth:/data
    restart: always
    logging: *default-logging
    labels:
      - logging=true
  virtuoso:
    image: redpencil/virtuoso:1.2.0-rc.1
    environment:
      SPARQL_UPDATE: true
      DEFAULT_GRAPH: http://mu.semte.ch/application
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini # Note: on production override this setting
      - ./config/virtuoso/:/opt/virtuoso-scripts
    restart: always
    logging: *default-logging
    labels:
      - logging=true
  migrations:
    image: semtech/mu-migrations-service:0.6.0
    environment:
      MU_SPARQL_TIMEOUT: 300
      MU_SPARQL_ENDPOINT: http://virtuoso:8890/sparql
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
    logging: *default-logging
    labels:
      - logging=true  
  modified:
    image: lblod/track-modified-service:0.0.1
    volumes:
      - ./config/modified:/config
    restart: always
    logging: *default-logging
    labels:
      - logging=true
